### ISSUE TITLE
Build on Java 8

### ISSUE THREAD

**Issue by andreldm** [danfickle/neoflyingsaucer#45]
I couldn't find jars for this project, so I had to build it by myself, but errors occurred. This thread on stackoverflow did the trick: http://stackoverflow.com/a/16743137

I know you want want to stick with Java 6 for now, but please provide the jars on maven central or use the fix provided on stackoverflow.

By the way, great project, thank you!

Cheers,
André Miranda

**Comment by PaulWallace** [comment]
+1 for jars on maven central. This is a really interesting project.

**Comment by danfickle** [comment]
Thanks for your interest guys.

I'm working on getting a maven release ready. The main blocker is putting cancel opportunities in the core so that it can be cancelled in the event of an endless loop. Also housekeeping such as consistent module names and documentation. 

In regard to build errors, I did work correcting javadoc errors a while ago, but must have introduced some again. Probably the best solution for now is to skip javadoc generation. The stackoverflow article says how.
http://stackoverflow.com/questions/7412016/how-can-i-disable-the-maven-javadoc-plugin-from-the-command-line

I'll put a note in the readme on building when I next touch the code.

Thanks again.

**Comment by andreldm** [comment]
Yep, `mvn package -Dmaven.javadoc.skip=true` does the trick.
Though jars on maven central is much better than build them :smile:
Thanks.
